main: net.lukeiscoding.spigot.usefulcommands.UsefulCommands
name: UsefulCommands
version: 0.1.0
author: LukeIsCoding

commands:
  clearchat:
    description: Clears the chat if someone said something bad or self promotion.
    permission: usefulcommands.clearchat
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    defualt: op
  testgui:
    description: Opens a test gui
    permission: usefulcommands.testgui
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    default: op
  usefulcommands:
    description: Accesses the admin gui for admins.
    permission: usefulcommands.admin
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    default: op
  destoryitems:
    description: Opens a GUI that players can place items in to be destroyed
    permission: usefulcommands.destroyitems
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    default: op
  crafting:
    description: Opens a crafting table / workbench
    permission: usefulcommands.crafting
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    default: op
  fly:
    description: Turns flight mode on or off
    permission: usefulcommands.fly
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    default: op
  smelt:
    description: Opens a furnace
    permission: usefulcommands.smelt
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    default: op
  nick:
    description: Sets your own nickname or another player's nicknamne.
    permission: usefulcommands.nick
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    default: op
  destroy:
    description: Opens a gui that players can place items to and when the player closes the gui the items get destroyed
    permission: usefulcommands.destroy
    permission-message: I am sorry but you do not have permission to use this command, please contact a server admin if you think this is an error.
    default: op